// Generated by CoffeeScript 1.12.7
(function() {
  var Auth, Item, Mercadolivre, Messages, Orders, Payments, Questions, Rest, Rest_browser, Rest_node, Search, Shipping, Users, Utils, _, config, https, log, querystring;

  log = require('debug')('log');

  _ = require("lodash");

  querystring = require('querystring');

  https = require('https');

  Auth = {};


  /* @get_token - Ensure always send last valid token */

  Auth.get_token = (function(_this) {
    return function(callback) {
      if (config.session && (config.session.access_token != null)) {
        if (config.session.access_token.invalid != null) {
          return Auth._refresh_token(callback);
        }
        return callback(config.session);
      } else {
        return Auth.from_client_credentials(callback);
      }
    };
  })(this);


  /* @set_token - */

  Auth.set_token = function(new_token) {
    return config.session = new_token;
  };

  Auth.set_apikey = function(keychain) {
    config.client_id = keychain.client_id;
    return config.client_secret = keychain.client_secret;
  };

  Auth.from_client_credentials = function(callback) {
    var data;
    data = {
      grant_type: "client_credentials",
      client_id: config.client_id,
      client_secret: config.client_secret
    };
    return Rest._post("/oauth/token", null, data, function(err, data) {
      console.log("response:", data);
      config.session = {};
      config.session.access_token = data.access_token;
      config.session.seller_id = data.user_id;
      console.log(config.session);
      return callback(err, config.session);
    });
  };

  Auth.from_authorization_code = function(code, redirect_uri, callback) {
    var data;
    data = {
      grant_type: "authorization_code",
      client_id: config.client_id,
      client_secret: config.client_secret,
      code: code,
      redirect_uri: redirect_uri
    };
    return Rest._post("/oauth/token", data, null, function(err, data) {
      console.log("response:", data);
      config.session = {};
      config.session.access_token = data.access_token;
      config.session.seller_id = data.user_id;
      config.session.refresh_token = data.refresh_token;
      console.log(config.session);
      return callback(err, config.session);
    });
  };


  /* TODO: working here */

  Auth.from_refresh_token = function(callback) {
    var data;
    data = {
      grant_type: "refresh_token",
      client_id: config.client_id,
      client_secret: config.client_secret,
      refresh_token: config.session.refresh_token
    };
    return Rest._post("/oauth/token", data, null, function(err, data) {
      console.log("response:", data);
      config.session = {};
      config.session.access_token = data.access_token;
      config.session.seller_id = data.user_id;
      config.session.refresh_token = data.refresh_token;
      return callback(err, config.session);
    });
  };

  config = {};

  Item = {};


  /* @get_item - */

  Item.get_item = function(item_id, callback) {
    return Rest._get("/items/" + item_id, null, callback);
  };


  /* @from_authenticated_seller - Fetch one order API Call */

  Item.from_authenticated_seller = function(seller, filter, callback) {
    return Auth.get_token(function() {
      var data;
      data = _.extend({}, filter, config.session);
      return Utils.paginate(Rest._get, "/users/" + seller + "/items/search", data, callback);
    });
  };


  /* @status - Fetch one order API Call */

  Item.status = function(seller, callback) {
    return Auth.get_token(function() {
      var data;
      data = _.extend({}, config.session, {
        status: 'active'
      });
      return Utils.paginate(Rest._get, "/users/" + seller + "/items/search", data, function(active) {
        data = _.extend(data, {
          status: 'paused'
        });
        return Utils.paginate(Rest._get, "/users/" + seller + "/items/search", data, function(paused) {
          data = _.extend(data, {
            status: 'closed'
          });
          return Utils.paginate(Rest._get, "/users/" + seller + "/items/search", data, function(closed) {
            return callback({
              active: active,
              paused: paused,
              closed: closed
            });
          });
        });
      });
    });
  };


  /* @get_item_and_description - */

  Item.with_description = function(item_id, callback) {
    return Rest._get("/items/" + item_id, {}, function(err_1, product) {
      if (err_1) {
        return callback(true, null);
      }
      return Rest._get("/items/" + item_id + "/description", {}, function(err_2, description) {
        if (err_2) {
          return callback(false, product);
        }
        return callback(false, _.extend({}, product, description));
      });
    });
  };

  Item.description = function(item_id, callback) {
    return Rest._get("/items/" + item_id + "/description", null, callback);
  };


  /* @save_item - */

  Item.save = function(item, callback) {
    return Auth.get_token(function() {
      var access_token, ref, seller_id;
      ref = config.session, seller_id = ref.seller_id, access_token = ref.access_token;
      return Rest._post("/items", {
        seller_id: seller_id,
        access_token: access_token
      }, item, callback);
    });
  };


  /* @update_item - */

  Item.update = function(item_id, payload, callback) {
    return Auth.get_token(function() {
      var access_token;
      access_token = config.session.access_token;
      return Rest._put("/items/" + item_id, {
        access_token: access_token
      }, payload, callback);
    });
  };

  Item.update_description = function(item_id, payload, callback) {
    return Auth.get_token(function() {
      var access_token;
      access_token = config.session.access_token;
      return Rest._put("/items/" + item_id + "/description", {
        access_token: access_token
      }, payload, callback);
    });
  };

  Item.get_variations = function(item_id, callback) {
    return Rest._get("/items/" + item_id + "/variations", null, callback);
  };

  Item.get_item_own = function(item_id, callback) {
    return Rest._get("/items/" + item_id, null, callback);
  };

  Messages = {};


  /* @get_question - Fetch one order API Call */

  Messages.get_message = function(_id, callback) {
    return Auth.get_token(function() {
      return Rest._get("/messages/" + _id, _.pick(config.session, ['access_token', 'seller_id']), callback);
    });
  };

  Orders = {};


  /* @get_order - Fetch one order API Call */

  Orders.get_order = function(order_id, callback) {
    return Auth.get_token(function() {
      return Rest._get("/orders/" + order_id, _.pick(config.session, ['access_token', 'seller_id']), callback);
    });
  };


  /* @ready_to_ship - */

  Orders.ready_to_ship = function(seller_id, callback) {
    return Auth.get_token(function() {
      var data;
      data = {
        "access_token": config.session.access_token,
        "seller": seller_id,
        "shipping.status": "ready_to_ship",
        "shipping.substatus": "ready_to_print"
      };
      console.log(data);
      return Orders.recent(data, callback);
    });
  };


  /* @recent */

  Orders.recent = function(data, callback) {
    return Rest._get("/orders/search/recent", data, function(response) {
      console.log("TOTAL: " + response.paging.total);
      return callback(response.results);
    });
  };


  /* @orders - Orders Search API Call */

  Orders.orders = function(data, callback) {
    return Rest._get("/orders/search", data, function(response) {
      log(response);
      return callback(response.results);
    });
  };


  /* @touch_orders - Orders Search API Call */

  Orders.touch_orders = function(data, callback) {
    var _data;
    _data = _.extend({}, data);
    return Rest._get("/orders/search", _data, function(response) {
      log(response);
      return callback(response.paging.total);
    });
  };


  /* @search_orders - Orders Search API Call */

  Orders.search_orders = function(seller, filter, callback) {
    return Auth.get_token(function() {
      var data;
      data = {
        access_token: config.session.access_token,
        seller: seller
      };
      data = _.extend(data, filter);
      return _paginate(Rest._get, "/orders/search", data, callback);
    });
  };


  /* @pending_orders - Orders Search API Call */

  Orders.pending_orders = function(seller, offset, callback) {
    return Auth.get_token(function() {
      var data;
      data = {
        access_token: config.session.access_token,
        seller: seller,
        offset: offset || 0
      };
      return Rest._get("/orders/search/pending", data, callback);
    });
  };


  /* @archived_orders - Orders Search API Call */

  Orders.archived_orders = function(seller, offset, callback) {
    return Auth.get_token(function() {
      var data;
      data = {
        access_token: config.session.access_token,
        seller: seller,
        offset: offset || 0
      };
      return Rest._get("/orders/search/archived", data, callback);
    });
  };

  Payments = {};


  /* @get_question - Fetch one order API Call */

  Payments.get_payment = function(_id, callback) {
    return Auth.get_token(function() {
      return Rest._get("/collections/" + _id, _.pick(config.session, ['access_token', 'seller_id']), callback);
    });
  };

  Questions = {};


  /* @unanswered - */

  Questions.unanswered = function(callback) {
    return Auth.get_token(function() {
      var data;
      data = {
        "access_token": config.session.access_token,
        "seller": config.session.seller_id,
        "status": "UNANSWERED"
      };
      return Rest._get("/questions/search", data, callback);
    });
  };


  /* @get_question - Fetch one order API Call */

  Questions.get_question = function(question_id, callback) {
    return Auth.get_token(function() {
      return Rest._get("/questions/" + question_id, _.pick(config.session, ['access_token', 'seller_id']), callback);
    });
  };

  Rest_browser = function() {
    var host;
    host = "https://api.mercadolibre.com";
    this._get = function(endpoint, query, callback) {
      var url, xhr;
      endpoint += '?' + querystring.stringify(query);
      xhr = new XMLHttpRequest();
      url = "" + host + endpoint;
      xhr.open("GET", url, true);
      xhr.setRequestHeader('x-format-new', true);
      xhr.onreadystatechange = function() {
        var data;
        if (this.readyState !== 4) {
          return;
        }
        if (this.status === 200) {
          data = JSON.parse(this.responseText);
          callback(false, data);
        }
        if (this.status === 401) {
          data = this.responseText;
          return callback(true, data);
        }
      };
      return xhr.send(null);
    };
    this._post = function(endpoint, query, data, callback) {
      var url, xhr;
      xhr = new XMLHttpRequest();
      url = "" + host + endpoint;
      xhr.open("POST", url, true);
      xhr.onreadystatechange = function() {
        if (this.readyState !== 4) {
          return;
        }
        if (this.status === 200) {
          data = JSON.parse(this.responseText);
          callback(false, data);
        }
        if (this.status === 401) {
          data = this.responseText;
          return callback(true, data);
        }
      };
      return xhr.send(JSON.stringify(data));
    };
    return this;
  };

  Rest_node = function() {
    var _request, host;
    host = "api.mercadolibre.com";
    this._get = function(endpoint, query, success) {
      return _request(endpoint, "GET", query, null, success);
    };
    this._post = function(endpoint, query, data, success) {
      return _request(endpoint, "POST", query, data, success);
    };
    this._put = function(endpoint, query, data, success) {
      return _request(endpoint, "PUT", query, data, success);
    };
    _request = function(endpoint, method, query, data, callback) {
      var dataString, headers, options, req;
      dataString = JSON.stringify(data);
      headers = {};
      endpoint += '?' + querystring.stringify(query);
      if (method === 'GET') {

      } else {
        headers = {
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(dataString, 'utf-8'),
          'x-format-new': true
        };
      }
      options = {
        host: host,
        path: endpoint,
        method: method,
        headers: headers
      };
      console.log(method + " => " + endpoint);
      req = https.request(options, function(res) {
        var responseString;
        res.setEncoding('utf-8');
        responseString = '';
        res.on('data', function(data) {
          return responseString += data;
        });
        return res.on('end', function() {
          var _response, err;
          try {
            _response = JSON.parse(responseString);
          } catch (error) {
            err = error;
            callback(true, err);
          }
          if (res.statusCode === 401) {
            return callback(true, _response);
          } else if (res.statusCode === 403) {
            return callback(true, _response);
          } else if (res.statusCode === 404) {
            return callback(true, _response);
          }
          return callback(false, _response);
        });
      });
      req.write(dataString);
      return req.end();
    };
    return this;
  };

  if (typeof window === 'undefined') {
    Rest = Rest_node();
  } else {
    Rest = Rest_browser();
  }

  Search = {};


  /* @single only one result - */

  Search.single = function(query_string, callback) {
    var data;
    data = {
      q: query_string,
      limit: 1
    };
    return Rest._get("/sites/MLB/search", data, callback);
  };


  /* @by_query - */

  Search.by_query = function(query_string, offset, callback) {
    var data;
    data = {
      q: query_string,
      offset: offset
    };
    return Rest._get("/sites/MLB/search", data, callback);
  };


  /* @by_url - */

  Search.by_url = function(query_string, callback) {
    var data;
    data = {
      q: query_string
    };
    return Rest._get("/sites/MLB/searchUrl", data, callback);
  };


  /* @items_from_seller - */

  Search.items_from_seller = function(seller_id, offset, callback) {
    var data;
    data = {
      seller_id: seller_id,
      offset: offset
    };
    return Rest._get("/sites/MLB/search", data, callback);
  };


  /* @items_from_seller_by_category - */

  Search.items_from_seller_by_category = function(seller_id, category_id, callback) {
    var data;
    data = {
      seller_id: seller_id,
      category: category_id
    };
    return Rest._get("/sites/MLB/search", data, callback);
  };


  /* @items_from_nickname - */

  Search.items_from_nickname = function(nickname, callback) {
    var data;
    data = {
      nickname: nickname
    };
    return Rest._get("/sites/MLB/search", data, callback);
  };

  Shipping = {};


  /* @get_order - Fetch one order API Call */

  Shipping.get_shipment = function(shipping_id, callback) {
    return Auth.get_token(function() {
      return Rest._get("/shipments/" + shipping_id, _.pick(config.session, ['access_token', 'seller_id']), callback);
    });
  };

  Users = {};


  /* @get_user - */

  Users.by_id = function(user_id, callback) {
    return Rest._get("/users/" + user_id, null, function(response) {
      return callback(response);
    });
  };

  module.exports = Users;

  Utils = {};


  /* @_is_updated_version compare two objects */

  Utils.is_an_updated_version = function(obj1, obj2) {
    if (obj1.date_created === obj2.date_created) {
      return true;
    } else {
      return false;
    }
  };


  /* @_is_it_the_same compare two objects */

  Utils.is_it_the_same = function(obj1, obj2) {
    if ((obj1.last_updated != null) && obj1.last_updated === obj2.last_updated) {
      return true;
    } else if (typeof obj1.date_last_updated === "function" ? obj1.date_last_updated(obj1.date_last_updated === obj2.date_last_updated) : void 0) {
      return true;
    } else {
      return false;
    }
  };


  /* @compare two lists and return the result */

  Utils.compare = function(old_list, new_list) {

    /* @result */
    var i, j, k, l, ref, ref1, result;
    result = {
      insert: new Array(),
      updated: new Array()
    };
    for (i = k = 0, ref = new_list.length - 1; 0 <= ref ? k <= ref : k >= ref; i = 0 <= ref ? ++k : --k) {
      for (j = l = 0, ref1 = old_list.length - 1; 0 <= ref1 ? l <= ref1 : l >= ref1; j = 0 <= ref1 ? ++l : --l) {
        if (this._is_an_updated_version(old_list[j], new_list[i])) {
          if (!this._is_it_the_same(old_list[j], new_list[i])) {
            result.updated.push(_.extend({}, old_list[j], new_list[i]));
          }
          break;
        } else if (j === old_list.length - 1) {
          result.insert.push(new_list[i]);
        }
      }
    }
    result.all_changes = _.extend({}, result.insert, result.updated);
    return result;
  };

  Utils.paginate = function(fn, url, params, callback, _yield) {
    var defaults;
    _yield = _yield || [];
    defaults = {
      offset: 0,
      limit: 50
    };
    params = _.extend({}, defaults, params);
    log(url, params);
    return fn(url, params, function(res) {
      log(res.results[0]);
      _yield = _.union(_yield, res.results);
      params.offset += res.paging.limit;
      if (res.paging.total > res.paging.offset + res.paging.limit) {
        return Utils.paginate(fn, url, params, callback, _yield);
      } else {
        return callback(_yield);
      }
    });
  };

  Mercadolivre = {
    Auth: Auth,
    Users: Users,
    Categories: {},
    Listings: {},
    Locations: {},
    Currencies: {},
    Item: Item,
    Search: Search,
    Orders: Orders,
    Questions: Questions,
    Messages: Messages,
    Feedback: {},
    Metrics: {},
    Shipping: Shipping,
    Payments: Payments
  };

  module.exports = Mercadolivre;

}).call(this);
